sparql:
  description: SPARQL description.
  variables: [DiseaseConcept, thing, upec, ecoli, cystitis, thing, mesh, pacdb, thing, pacdb_diseases, thing, disease, thing, tropism_in_reference, case, tropism_in_reference, species, paconto_strain, taxo, strain, mesh_id, pacdb_diseases, mesh_id]