- Naddentry nadd:monad0024:
  - a:
    - jst:Chemical
    - innovation:Innovation
  - obo:RO_0002606+:
    - disease: obo:MONDO_0005150 # age-related macular degeneration
  - innovation:developedBy+:
    - company: "OSI Eyetech, Inc"
    - wikidata: wikidata:Q663596 # Gilead Sciences, Inc.
  - sio:SIO_000223+: # has property
    - type_so: obo:SO_0000031 # aptamer
    - type_ncit: ncit:C1749
  - sio:SIO_000362+: # satisfies
    - []:
      - a: ncit:C15206
      - phase: {{expand blank node}}
  - sio:SIO_000671+: # has identifier
    - atc: uatc:S01LA03
  - sio:SIO_010423+: # target
    - uniprot_id: uniprot:P15692 # uniprot:P15692
    - datablock: pdbr:3BDY
  - rdfs:comment+:
    - comment1: "Macugen is used for the treatment of angiogenic age-related macular degeneration (AMD)."
    - comment2: "Macugen is used for the treatment of angiogenic age-related macular degeneration (AMD)."
  - rdfs:label+:
    - sequence1: "((2'-deoxy-2'-fluoro)C-Gm-Gm-A-A-(2'-deoxy-2'-fluoro)U-(2'-deoxy-2'-fluoro)C-Am-Gm-(2'-deoxy-2'-fluoro)U-Gm-Am-Am-(2'-deoxy-2'-fluoro)U-Gm-(2'-deoxy-2'-fluoro)C-(2'-deoxy-2'-fluoro)U-(2'-deoxy-2'fluoro)U-Am-(2'-deoxy-2'-fluoro)U-Am-(2'-deoxy-2'-fluoro)C-Am-(2'-deoxy-2'-fluoro)U-(2'deoxy-2'-fluoro)C-(2'-deoxy-2'-fluoro)C-Gm-(3'→3')-dT), 5'-ester with α,α'-[4,12-dioxo-6[[[5-(phosphoonoxy)pentyl]amino] carbonyl]-3,13-dioxa-5,11-diaza-1,15pentadecanediyl]bis[ω-methoxypoly(oxy-1,2-ethanediyl)]"
    - sequence2: "((2'-deoxy-2'-fluoro)C-Gm-Gm-A-A-(2'-deoxy-2'-fluoro)U-(2'-deoxy-2'-fluoro)C-Am-Gm-(2'-deoxy-2'-fluoro)U-Gm-Am-Am-(2'-deoxy-2'-fluoro)U-Gm-(2'-deoxy-2'-fluoro)C-(2'-deoxy-2'-fluoro)U-(2'-deoxy-2'fluoro)U-Am-(2'-deoxy-2'-fluoro)U-Am-(2'-deoxy-2'-fluoro)C-Am-(2'-deoxy-2'-fluoro)U-(2'deoxy-2'-fluoro)C-(2'-deoxy-2'-fluoro)C-Gm-(3'→3')-dT), 5'-ester with α,α'-[4,12-dioxo-6[[[5-(phosphoonoxy)pentyl]amino] carbonyl]-3,13-dioxa-5,11-diaza-1,15pentadecanediyl]bis[ω-methoxypoly(oxy-1,2-ethanediyl)]"
  - rdfs:seeAlso+:
    - source: clinicaltrial:DE
  - skos:altLabel+:
    - product_name: "Macugen"

