glycan: <http://purl.jp/bio/12/glyco/glycan#>
p0: <http://rdf.glycoinfo.org/glycan/>
p1: <http://rdf.glycoinfo.org/glycan/02513e64ba7686c21e13fdbc227d338602ed1aefe5e827273c81818de17f7522/wurcs/>
p3: <http://rdf.glycoinfo.org/glycan/02513e64ba7686c21e13fdbc227d338602ed1aefe5e827273c81818de17f7522/wurcs/2.0/LIN/>
p6: <http://rdf.glycoinfo.org/glycan/02513e64ba7686c21e13fdbc227d338602ed1aefe5e827273c81818de17f7522/wurcs/2.0/RES/>
p7: <http://rdf.glycoinfo.org/glycan/02513e64ba7686c21e13fdbc227d338602ed1aefe5e827273c81818de17f7522/wurcs/2.0/UniqueRES/>
p8: <http://rdf.glycoinfo.org/glycan/wurcs/2.0/>
p4: <http://rdf.glycoinfo.org/glycan/wurcs/2.0/Basetype/>
p10: <http://rdf.glycoinfo.org/glycan/wurcs/2.0/GLIP/>
p9: <http://rdf.glycoinfo.org/glycan/wurcs/2.0/GLIPS/>
p5: <http://rdf.glycoinfo.org/glycan/wurcs/2.0/Monosaccharide/>
p11: <http://rdf.glycoinfo.org/glycan/wurcs/2.0/RES/>
wurcs: <http://www.glycoinfo.org/glyco/owl/wurcs#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
owl: <http://www.w3.org/2002/07/owl#>