sparql:
  description: RDFized reference gene expresson dataset derived from CAGE and GeneChip experiments in the RefEx database.
  variables: [refex_id, see_also, RefExSample, disease]
  #subject: RefEx_Sample
  #variables: [sample_id, taxonomy, class10, class40, sex, unique_order, ref_description, sample_category, cell_type]
  #variables: [disease, dev_site, refexo_sample]
