- PubChemCompound compound:CID3835861:
  # - a*:
  #   - compound_class: obo:CHEBI_121361
  - sio:has-attribute*:  # 正しくは SIO_000008
    - compound_attribute: [PubChemDescriptor, PubChemSynonym]
  - sio:CHEMINF_000461*:              # is_stereoisomer_of
    - compound_stereoisomer: PubChemCompound
  - skos:closeMatch*:
    - compound_close_match: <http://www.wikidata.org/entity/Q27209899>
  - pubchemv:is_active_ingredient_of*:
    - compound_active_ingredient: PubChemCompound
  - sio:CHEMINF_000455*:  # is_isotopologue_of
    - compound_isotopologue: PubChemCompound
  - sio:CHEMINF_000480*:  # has component with uncharged counterpart
    - compound_uncharged_counterpart: PubChemCompound
  - sio:CHEMINF_000462*:  # has_same_connectivity_as
    - compound_same_connectivity*: PubChemCompound
  - pubchemv:has_parent*:
    - compound_parent: PubChemCompound
  - obo:has-role?:        # 正しくは RO_0000087 あるいは SIO_000228
    - compound_role: pubchemv:FDAApprovedDrugs

- PubChemSubstance substance:SID3712803:
  # - a*:
  #   - substance_class: obo:CHEBI_121361
  - dcterms:modified:
    - substance_modified: 2012-03-01-04:00
  - sio:has-attribute*:
    - substance_attribute: [PubChemDescriptor, PubChemSynonym]
  - dcterms:source:
    - substance_source: PubChemSource
  - obo:RO_0000056*:                  # participates in
    - substance_participates_in: PubChemMeasureGroup
  - sio:CHEMINF_000477*:              # has PubChem normalized counterpart
    - substance_normalized_counterpart: PubChemCompound
  - dcterms:available:
    - substance_available: 2005-07-30-04:00
  - cito:isDiscussedBy*:
    - substance_reference: PubChemReference
  - skos:exactMatch*:
    - substance_exact_match: <http://rdf.ebi.ac.uk/resource/chembl/molecule/CHEMBL1337170>
  - pdbo:link_to_pdb*:
    - substance_link_to_pdb: <http://rdf.wwpdb.org/pdb/2MX6>

- PubChemBioAssay bioassay:AID610:
  - a: bao:BAO_0000015                # bioassay
  - dcterms:source:
    - bioassay_source: PubChemSource
  - dcterms:title:
    - bioassay_title: '"Dose-response cell-based assay"@en'
  - bao:BAO_0000209*:                 # has measure group
    - bioassay_measure_group: PubChemMeasureGroup
  - bao:BAO_0000210*:                 # has assay stage
    - bioassay_assay_stage: bao:BAO_0000030    # confirmatory assay
  - bao:BAO_0000540*:                 # is confirmatory assay of
    - bioassay_confirmatory_assay_of: PubChemBioAssay
  # - bao:BAO_0000808*:                 # has primary assay
  #   - primary_assay: bioassay:AID561
  # - bao:BAO_0000809*:                 # has confirmatory assay
  #   - confirmatory_assay: bioassay:AID610
  # - bao:BAO_0000812*:                 # has summary assay
  #   - summary_assay: bioassay:AID2139
  - bao:BAO_0001067*:                 # is primary assay of
    - bioassay_primary_assay_of: PubChemBioAssay
  - bao:BAO_0001094*:                 # is summary assay of
    - bioassay_summary_assay_of: PubChemBioAssay
  - biopax:organism:
    - bioassay_organism: PubChemTaxonomy
  - cito:isDiscussedBy*:
    - bioassay_reference: PubChemPatent  # PubChemReference はない。

- PubChemConcept concept:ATC_A01AA:
  - a: skos:concept
  - pav:importedFrom:
    - concept_imported_from: PubChemSource
  - skos:broader:
    - concept_broader: PubChemConcept
  - skos:inScheme:
    - concept_in_scheme: PubChemConcept
  - skos:prefLabel:
    - concept_label: "stomatological preparations"

- PubChemConservedDomain conserveddomain:PSSMID100030:
  # - a:
  #   - conserveddomain_type: obo:SO_0000417  # polypeptide_domain
  - dcterms:title:
    - conserveddomain_title: '"ThiL"@en'
  - cito:isDiscussedBy:
    - conserveddomain_reference: PubChemReference
  - dcterms:abstract:
    - conserveddomain_abstract: '"ThiL (Thiamine-monophosphate kinase) plays a dual role in ..."@en'

- PubChemDescriptor descriptor:CID3835107_Covalent_Unit_Count:
  # - a:
  #   - descriptor_type: sio:CHEMINF_000369
  - sio:has-value:  # 正しくは SIO_000300
    - descriptor_value: 1

- PubChemGene gene:GID10000:
  - a: biopax:Gene
  - dcterms:title:
    - gene_name: '"AKT serine/threonine kinase 3"@en'
  - biopax:organism:
    - gene_organism: PubChemTaxonomy
  - skos:closeMatch*:
    - gene_close_match: <http://rdf.ebi.ac.uk/resource/ensembl/ENSG00000117020>
  - dcterms:alternative*:
    - gene_alternative_name: '"MPPH"@en'
  - sio:gene-symbol:  # SIO_001383 だと思われるが、だとしてもこれはクラスなので誤り。
    - gene_symbol: '"AKT3"@en'
  - obo:RO_0000056*:    # participates in
    - gene_participates_in: obo:GO_1905653  # GO BP
  - obo:RO_0000085*:    # has function
    - gene_has_function: obo:GO_0005524     # GO MF
  - obo:RO_0001025*:    # located in
    - gene_located_in: obo:GO_0016020       # GO CC
  - cito:isDiscussedBy*:
    - gene_reference: PubChemReference

- PubChemEndpoint endpoint:SID103164874_AID443491:
  # - a:
  #   - endpoint_type: bao:BAO_0000190  # IC50
  - obo:IAO_0000136:                  # is about
    - endpoint_is_about: PubChemSubstance
  - sio:has-unit:  # SIO_000221
    - endpoint_has_unit: obo:UO_0000064            # cubic meter
  - sio:has-value: # SIO_000300
    - endpoint_has_value: 0.162
  - rdfs:label:
    - endpoint_label: '"IC50"@en'
  - pubchemv:PubChemAssayOutcome:
    - endpoint_assay_outcome: pubchemv:active
  - cito:citesAsDataSource:
    - endpoint_cites_as_data_source: PubChemReference

- PubChemInchiKey inchikey:AAAHDTMMJGSHKG-UHFFFAOYSA-N:
  - a: sio:CHEMINF_000399  # InChIKey generated by software version 1.0.4
  - sio:has-value:
    - inchikey_has_value: '"AAAHDTMMJGSHKG-UHFFFAOYSA-N"@en'
  - sio:is-attribute-of:
    - inchikey_is_attribute_of: PubChemCompound

- PubChemPatent patent:US-2018127469-A1:
  - a: epo_patent:Publication
  - dcterms:abstract:
    - patent_abstract: "In one aspect, the invention relates to substituted urea depsipeptide analogs, ..."
  - epo_patent:classificationCPCAdditional:
    - patent_classification_cpc_additional: pubchem:patentcpc/Y02A50-30
  - epo_patent:classificationIPCAdditional:
    - patent_classification_ipc_additional: pubchem:patentipc/A61K38-00
  - epo_patent:applicantVC:
    - patent_applicant_vc: pubchem:patentassignee/MD5_ec3d7a9a543c4214ef75cdabb2d0e04b
  - epo_patent:inventorVC:
    - patent_inventor_vc: pubchem:patentinventor/MD5_4629043bf5f853a34a4429f98a8b3471
  - epo_patent:classificationIPCInventive:
    - patent_classification_ipc_inventive: pubchem:patentipc/A61K38-15
  - epo_patent:classificationCPCInventive:
    - patent_classification_cpc_inventive: pubchem:patentcpc/C07K11-02
  - cito:isCitedBy:
    - patent_is_cited_by: PubChemPatent
  - epo_patent:filingDate:
    - patent_filing_date: 2018-01-05-04:00
  - epo_patent:publicationNumber:
    - patent_publication_number: '"US-2018127469-A1"@en'

- PubChemMeasureGroup measuregroup:AID600004:
  - a: bao:BAO_0000040                # measure group
  - obo:OBI_0000299:                  # has specified output
    - measuregroup_endpoint: PubChemEndpoint
  - dcterms:title:
    - measure_group_title: '"Inhibition of human FLT3 using gamma-33P-ATP as substrate by scintillation counting"@en'
  - obo:RO_0000057*:
    - measuregroup_participant: [PubChemProtein, PubChemGene]
  - dcterms:source:
    - measuregroup_source: PubChemSource

- PubChemPathway pathway:PWID1:
  - a: biopax:Pathway
  - dcterms:title:
    - pathway_title: '"Glycolysis"@en'
  - biopax:organism:
    - pathway_organism: PubChemTaxonomy
  - dcterms:source:
    - pathway_source: PubChemSource
  - cito:isDiscussedBy*:
    - pathway_reference: PubChemReference
  - obo:RO_0000057+:
    - pathway_participant: [PubChemCompound, PubChemProtein]
  - biopax:pathwayComponent+:
    - pathway_component: [PubChemPathway, PubChemReaction]
  - skos:exactMatch*:
    - pathway_exact_match: <http://identifiers.org/reactome/R-HSA-70171>
  - skos:related*:
    - pathway_related: PubChemPathway

# protein:ACC1DAR_A のように ACC[PDB ID]_[Chain] 式のものと、
# protein:ACCP19157 のように ACC[UniProt ID] 式のものがいる。
# 持っているプロパティは両者で若干異なる。UniProt はクラスとして PRO (Protein Ontology) のクラスを持っている。obo:PR_P19157 や obo:PR_000035159 など。
- PubChemProtein protein:ACC1DAR_A:
  - a: biopax:Protein
  # - a:
  #   - protein_class:
  - dcterms:title:
    - protein_name: '"Chain A, Elongation Factor G"@en'
  - biopax:organism:
    - protein_organism: PubChemTaxonomy
  - skos:closeMatch:
    - protein_close_match: <https://www.ncbi.nlm.nih.gov/protein/WP_011228848.1>  # あるいは UniProt
  - up:encodedBy:
    - protein_encoded_by: PubChemGene
  - pubchemv:hasSimilarProtein:
    - protein_similar_protein: PubChemProtein
  - obo:RO_0002180:  # has component
    - protein_has_component: PubChemConservedDomain
  - pdbo:link_to_pdb*:
    - protein_link_to_pdb: <http://rdf.wwpdb.org/pdb/1DAR>

# PubChemReaction ## pathway の component として出てくるが、そこ以外にいない。
## pubchem:reaction/PWID1BiochemicalReaction6972

- PubChemReference reference:PMID10021376:
  - a: fabio:ReviewArticle
  - a: fabio:JournalArticle
  - dcterms:title:
    - reference_title: '"Intracellular signalling: PDK1--a kinase at the hub of things"@en'
  - cito:discusses*:
    - reference_discusses: <http://id.nlm.nih.gov/mesh/M0011758>
  - dcterms:bibliographicCitation:
    - reference_bibliographic_citation: "C Belham, S Wu, J Avruch; Current biology : CB; 1999 Feb; 9(3):R93-6"
  - dcterms:date:
    - reference_date: 1999-02-11-04:00
  - fabio:hasSubjectTerm*:
    - reference_subject_term: <http://id.nlm.nih.gov/mesh/D000818>
  - fabio:hasPrimarySubjectTerm*:
    - reference_primary_subject_term: <http://id.nlm.nih.gov/mesh/D011499>

- PubChemSource source:IUPHAR_DB:  # DB や機関の名前が ID として URI に使われている場合と、"ID22070" のような ID が使われている場合とがある。
  - a: dcterms:Dataset  # そんなクラスで大丈夫？
  - dcterms:title:
    - source_title: '"IUPHAR-DB"@en'
  - dcterms:alternative:
    - source_alternative: '"IUPHAR/BPS Guide to PHARMACOLOGY"@en'
  - dcterms:subject*:
    - source_subject: PubChemConcept
  - foaf:homepage:
    - source_homepage: <https://www.guidetopharmacology.org/>
  - dcterms:license:
    - source_license: <https://www.guidetopharmacology.org/about.jsp#license>
  - dcterms:rights:
    - source_rights: '"The Guide to PHARMACOLOGY database is licensed under the..."@en'

- PubChemTaxonomy taxonomy:TAXID10090:
  - a: biopax:taxonomy
  - dcterms:title:
    - taxonomy_name: '"Mus musculus (house mouse)"@en'
  - skos:closeMatch*:
    - taxonomy_close_match: <https://www.uniprot.org/taxonomy/10090>

- PubChemSynonym synonym:MD5_1036ded866e2323b054cc79847c46ff6:
  # - a:
  #   - synonym_type: sio:CHEMINF_000467
      # sio:CHEMINF_000467 (validated chemical database identifier)
      # sio:CHEMINF_000446 (CAS registry number)
      # sio:CHEMINF_000339 (pubchem depositor-supplied molecular entity name)
      # etc.
  - sio:has-value:
    - synonym_value: '"3M-001"@en'
  - sio:is-attribute-of:
    - synonym_is_attribute_of: PubChemCompound
      # Substance もありそうだがない
  - dcterms:subject*:
    - synonym_subject: <http://id.nlm.nih.gov/mesh/M0517923>

- PubChemCompoundCompoundCooccurrence cooccurrence:CID135391179_CID10112:
  - a: sio:SIO_001435  # chemical-chemical association
  - rdf:subject:
    - compound_compound_cooccurrence_subject: PubChemCompound
  - rdf:object:
    - compound_compound_cooccurrence_object: PubChemCompound
  - sio:SIO_001157:    # is result of
    - compound_compound_cooccurrence_operation: edam:operation_0306  # Text mining
  - sio:SIO_000300:    # has value
    - compound_compound_cooccurrence_score: 16

- PubChemCompoundGeneCooccurrence cooccurrence:CID10009279_ASE1:
  - a: sio:SIO_001257  # chemical-gene association
  - rdf:subject:
    - compound_gene_cooccurrence_subject: [PubChemCompound, PubChemGene]  # subject が compound で object が gene の場合だけでなく逆向きもある。
  - rdf:object:
    - compound_gene_cooccurrence_object: [PubChemCompound, PubChemGene]
  - sio:SIO_001157:    # is result of
    - compound_gene_cooccurrence_operation: edam:operation_0306  # Text mining
  - sio:SIO_000300:    # has value
    - compound_gene_cooccurrence_score: 16

- PubChemCompoundDiseaseCooccurrence cooccurrence:CID10007406_DZID7548:
  - a: sio:SIO_000993  # chemical-disease association
  - rdf:subject:
    - compound_disease_cooccurrence_subject: [PubChemCompound, PubChemDisease]
  - rdf:object:
    - compound_disease_cooccurrence_object: [PubChemCompound, PubChemDisease]
  - sio:SIO_001157:    # is result of
    - compound_disease_cooccurrence_operation: edam:operation_0306  # Text mining
  - sio:SIO_000300:    # has value
    - compound_disease_cooccurrence_score: 16

- PubChemDiseaseDiseaseCooccurrence cooccurrence:DZID11429_DZID10258:
  - a: sio:SIO_001436  # disease-disease association
  - rdf:subject:
    - disease_disease_cooccurrence_subject: PubChemDisease
  - rdf:object:
    - disease_disease_cooccurrence_object: PubChemDisease
  - sio:SIO_001157:    # is result of
    - disease_disease_cooccurrence_operation: edam:operation_0306  # Text mining
  - sio:SIO_000300:    # has value
    - disease_disease_cooccurrence_score: 16

- PubChemDiseaseGeneCooccurrence cooccurrence:APOA2_DZID7001:
  - a: sio:SIO_000983  # gene-disease association
  - rdf:subject:
    - disease_gene_cooccurrence_subject: [PubChemDisease, PubChemGene]
  - rdf:object:
    - disease_gene_cooccurrence_object: [PubChemDisease, PubChemGene]
  - sio:SIO_001157:    # is result of
    - disease_gene_cooccurrence_operation: edam:operation_0306  # Text mining
  - sio:SIO_000300:    # has value
    - disease_gene_cooccurrence_score: 16

- PubChemGeneGeneCooccurrence cooccurrence:GTF2B_ABCC2:
  - a: sio:SIO_001437  # gene-gene association
  - rdf:subject:
    - gene_gene_cooccurrence_subject: PubChemGene
  - rdf:object:
    - gene_gene_cooccurrence_object: PubChemGene
  - sio:SIO_001157:    # is result of
    - gene_gene_cooccurrence_operation: edam:operation_0306  # Text mining
  - sio:SIO_000300:    # has value
    - gene_gene_cooccurrence_score: 16

- PubChemAuthor author:MD5_8b1fbee829d0da8e2dbfabfad65d6338:
  # - a:  # クラスがない
  - vcard2006:family-name:
    - author_family_name: "Velders"
  - vcard2006:given-name+:  # "Aldrik H" と "Aldrik H." がある
    - author_given_name: "Aldrik H"
  - vcard2006:fn+:
    - author_full_name: "Aldrik H Velders"
  - vcard2006:organization-name*:
    - author_organization: "Leiden Institute of Chemistry, ..."

- PubChemAuthorOrcid author:ORCID_0000-0000-0000-0001:
  # - a:  # クラスがない
  - vcard2006:hasUID?:
    - author_uid: <https://orcid.org/0000-0000-0000-0001>
  - dcterms:source?:
    - author_source: <https://orcid.org>

- PubChemBook book:NBK10310:
  - a: fabio:Book
  - dcterms:creator:
    - book_creator: PubChemAuthor
  - dcterms:date:
    - book_date: "2006"
  - dcterms:publisher:
    - book_publisher: "Oregon Health & Science University"
  - dcterms:title:
    - book_title: "Drug Class Review: Alzheimer's Drugs"
  - prism:location:
    - book_location: "Portland (OR)"
  - skos:exactMatch:
    - book_exact_match: <https://www.ncbi.nlm.nih.gov/books/NBK10310>
  - prism:subtitle?:
    - book_subtitle: "Final Report"
  - prism:isbn?:
    - book_isbn: "0-8153-3642-X"

# - PubChemCell cell:id:
# - PubChemDisease disease:id:
# - PubChemGrant grant:id:
# - PubChemJournal journal:id:
# - PubChemOrganization organizaion:id:
