kero: <http://kero.hgc.jp/ontology/kero.owl#>
bsseqdata: <http://kero.hgc.jp/rdf/data/9/BSseq/>
bsseqdataset: <http://kero.hgc.jp/rdf/dataset/9/BSseq/>
chipseqdata: <http://kero.hgc.jp/rdf/data/9/ChIPseq/>
chipseqdataset: <http://kero.hgc.jp/rdf/dataset/9/ChIPseq/>
chromhmmdata: <http://kero.hgc.jp/rdf/data/9/ChromHMM/>
chromhmmdataset: <http://kero.hgc.jp/rdf/dataset/9/ChromHMM/>
rnaseqdata: <http://kero.hgc.jp/rdf/data/9/RNAseq/>
rnaseqdataset: <http://kero.hgc.jp/rdf/dataset/9/RNAseq/>
snvdata: <http://kero.hgc.jp/rdf/data/9/SNV/>
snvdataset: <http://kero.hgc.jp/rdf/dataset/9/SNV/>
tssseqdata: <http://kero.hgc.jp/rdf/data/9/TSSseq/>
tssseqdataset: <http://kero.hgc.jp/rdf/dataset/9/TSSseq/>
sample: <http://kero.hgc.jp/rdf/sample/>
species: <http://kero.hgc.jp/rdf/species/>
dct: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dcat: <http://www.w3.org/ns/dcat#>