prism: <http://prismstandard.org/namespeces/1.2/basic/>
bibo: <http://purl.org/ontology/bibo/>
olo: <http://purl.org/ontology/olo/core#>
pav: <http://purl.org/pav/>
fabio: <http://purl.org/spar/fabio/>
pubmed: <http://rdf.ncbi.nlm.nih.gov/pubmed/>
pubmedontology: <http:purl.jp/bio/10/pubmed/>
dct: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
foaf: <http://xmlns.com/foaf/0.1/>
sio: <http://semanticscience.org/resource/>
