title: Gene Ontology RDF
website: http://geneontology.org/
description: The Gene Ontology resource provides a computational representation of our current scientific knowledge about the functions of genes (or, more properly, the protein and non-coding RNA molecules produced by genes) from many different organisms, from humans to bacteria.
tags: [ Gene, Annotation ]
provider:
creators:
  - name: 
    affiliation: 
version: 2020-08-12
issued: 2020-09-14
licenses:
  - Creative Commons Attribution 4.0 Unported License (CC BY 4.0) Gene Ontology Consortium
