- GO <http://purl.obolibrary.org/obo/GO_0000001>:
    - a: owl:Class:
    	- obo:definition:
	    - definition: '"The distribution of mitochondria, including the mitochondrial genome, into daughter cells after mitosis or meiosis, mediated by interactions between mitochondria and the cytoskeleton."^^xsd:string'
    	- oboInOwl:hasExactSynonym:
	    - hasExactSynonym: '"mitochondrial inheritance"^^xsd:string'
    	- oboInOwl:hasOBONamespace:
	    - hasOBONamespace: '"biological_process"^^string'
    	- oboInOwl:id:
	    - id: '"GO:0000001"^^string'
    	- rdfs:label:
	    - label: '"mitochondrion inheritance"^^string'
    - a: owl:Axiom:
    	- owl:annotatedSource:
	    - resource: <http://purl.obolibrary.org/obo/GO_0000001>
	- owl:annotatedProperty:
	    - resource: <http://purl.obolibrary.org/obo/IAO_0000115>
	- owl:annotatedTarget:
	    - annotatedTarget: '"The distribution of mitochondria, including the mitochondrial genome, into daughter cells after mitosis or meiosis, mediated by interactions between mitochondria and the cytoskeleton."^^xsd:string'
	- oboInOwl:hasDbXref*:
	    - hasDbXref: '"GOC:mcc"^^xsd:string'
	    - hasDbXref: '"PMID:10873824"^^xsd:string'
	    - hasDbXref: '"PMID:11389764"^^xsd:string'
