rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dct: <http://purl.org/dc/terms/>
obo: <http://purl.obolibrary.org/obo/>
skos: <http://www.w3.org/2004/02/skos/core#>
go: <http://purl.obolibrary.org/obo/go#>

base: <http://purl.obolibrary.org/obo/go.owl>
dc: <http://purl.org/dc/elements/1.1/>
terms: <http://purl.org/dc/terms/>
terms1: <http://www.geneontology.org/formats/oboInOwl#http://purl.org/dc/terms/>
oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
