title: PolyInfo BDG_S, ID definition
website: https://polymer.nims.go.jp/
description: 生物分解プロジェクト、生物分解IDの定義。
tags: [Drug/Chemical]
provider: 国立研究開発法人物質・材料研究機構
creators:
  - name: 石井 真史
    affiliation: 国立研究開発法人物質・材料研究機構
version: 0.2
issued: 2020-02-06
license:
  - name: Creative Commons BY 4.0 International (CC BY 4.0) 
  - url: https://creativecommons.org/licenses/by/4.0/deed.ja
  - credit: CC BY 4.0 by National Institute for Materials Science (NIMS), Japan
