- Ddbjentry insdc:AP014957.1:
  - a: nucleotide:Entry
  - nucleotide:comment:
    - nucleotide_comment: ""
  - nucleotide:definition:
    - definition: "Oryza sativa Japonica Group DNA, chromosome 1, cultivar: Nipponbare, complete sequence."
  - nucleotide:division:
    - division: insdcdiv:PLN
  - nucleotide:organism:
    - organism: "Oryza sativa Japonica Group"
  - nucleotide:reference+:
    - insdc: entry:reference.1
  - nucleotide:sequence:
    - insdc: entry:sequence
  - nucleotide:sequence_date:
    - registered_date: 2015-10-10
  - nucleotide:sequence_version:
    - sequence_version: "AP014957.1"
  - nucleotide:source:
    - source: "Oryza sativa Japonica Group (Japanese rice)"
  - nucleotide:taxonomy:
    - taxonomy: "Eukaryota; Viridiplantae; Streptophyta; Embryophyta; Tracheophyta; Spermatophyta; Magnoliophyta; Liliopsida; Poales; Poaceae; BOP clade; Oryzoideae; Oryzeae; Oryzinae; Oryza."
  - rdfs:comment:
    - comment: "Oryza sativa Japonica Group DNA, chromosome 1, cultivar: Nipponbare, complete sequence."

