nucleotide: <http://ddbj.nig.ac.jp/ontologies/nucleotide/>
insdcdiv: <http://ddbj.nig.ac.jp/ontologies/nucleotide/Division#>
insdc: <http://identifiers.org/insdc/>
entry: <http://identifiers.org/insdc/AP014957.1#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>