nucleotide: <http://ddbj.nig.ac.jp/ontologies/nucleotide/>
insdcdiv: <http://ddbj.nig.ac.jp/ontologies/nucleotide/Division#>
insdc: <http://identifiers.org/insdc/>
entry: <http://identifiers.org/insdc/AP014957.1#>
reference: <http://ddbj.nig.ac.jp/ontologies/nucleotide/reference#>
region: <http://identifiers.org/insdc/AP014957.1#region:1-43270923:>
fetaure: <http://identifiers.org/insdc/AP014957.1#feature:1-43270923:1:>
taxonomy: <http://identifiers.org/taxonomy/>
data: <http://www.ebi.ac.uk/ena/data/view/>
faldo: <http://biohackathon.org/resource/faldo#>
position_start: <http://identifiers.org/insdc/AP014957.1#position:1:>
position_end: <http://identifiers.org/insdc/AP014957.1#position:43270923:>
obo: <http://purl.obolibrary.org/obo/>
sio: <http://semanticscience.org/resource/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
