taxonomy: <http://identifiers.org/taxonomy/>
probe: <http://purl.jp/bio/101/opentggates/Probe/>
array: <http://purl.jp/bio/101/opentggates/Array/>
chip: <http://purl.jp/bio/101/opentggates/Chip/>
ontology: <http://purl.jp/bio/101/opentggates/ontology/>
uniprot: <http://purl.uniprot.org/uniprot/>
dct: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>