- HGNC hgnc:11998:
  - a: m2r:Gene
  - rdfs:label:
    - gene: "TP53"
  - dct:description:
    - label: "tumor protein p53"
  - rdfs:seeAlso:
    - see_also: <http://identifiers.org/ncbigene/7157>, <http://identifiers.org/ensembl/ENSG00000141510>, <http://identifiers.org/refseq/NM_000546>, <http://identifiers.org/uniprot/P04637>, <http://identifiers.org/omim/191170>
  - dct:references:
    - reference*: <http://identifiers.org/pubmed/20498374>
  - skos:altLabel:
    - alt_label*: "p53"
