sparql:
  description: Obrain gene records from the HGNC data
  variables: [gene_id, hgnc_id, label, location, ncbigene_id, ensembl_id, uniprot_id, pubmed_id]

stanza_sparql:
  description: Obtain a gene record from the HGNC data
  parameters:
    gene: TP53
  variables: [gene_id, label, see_also, reference, alt_label]

