sparql:
  description: Obrain gene records from the HGNC data
  variables: [gene_id, hgnc_id, description, location, ncbigene_id, ensembl_id, insdc_id, refseq_id, uniprot_id, pubmed_id, omim_id]

stanza_sparql:
  description: Obtain a gene record from the HGNC data
  parameters:
    gene: TP53
  variables: [gene_id, description, see_also, pubmed_id, alt_label]

