sparql:
  description: get InChI InChIkey for a compound
  variables: [Compound,  inchi_value, inchikey_value, IsomericSMILES, isomeric_smiles_value]
  options:
    distinct: true
sparql_atc:
  description: get ATC code for a compound
  variables: [compound_with_inn, INN,  ATC, atc_label, parent_atc]
  options:
    distinct: true
