- Concept ggdonto:CON00634:
  - a:
    - skos:Concept
    - ggdonto_schema:DiseaseDescriptionGGDonto
  - gdgdb_schema:omimPhenoMIMnumber+:
    - omim_id: "601776"
  - ggdonto_schema:brArthrogryposisGD+:
    - clinical_findings_description: ggdonto:CON00443 # Arthrogryposis
  - ggdonto_schema:brCleftPalateMouthAbnormGD+:
    - concept: ggdonto:CON00458 # Cleft Palate
  - ggdonto_schema:brCleftPalateMusculoskeletalAbnormGD+:
    - concept: ggdonto:CON00458 # Cleft Palate
  - ggdonto_schema:brCleftPalateStomatognathicAbnormGD+:
    - concept: ggdonto:CON00458 # Cleft Palate
  - ggdonto_schema:brClubfootGD+:
    - concept: ggdonto:CON00459 # Clubfoot
  - ggdonto_schema:brConnectiveTissueDisGD+:
    - concept: ggdonto:CON00139 # Connective Tissue Diseases
  - ggdonto_schema:brContractureGD+:
    - concept: ggdonto:CON00141 # Contracture
  - ggdonto_schema:brCornealDystrophHeredCornealDisGD+:
    - clinical_findings_description: ggdonto:CON00464 # Corneal Dystrophies, Hereditary
  - ggdonto_schema:brCornealDystrophHeredGD+:
    - clinical_findings_description: ggdonto:CON00464 # Corneal Dystrophies, Hereditary
  - ggdonto_schema:brCraniofacialAbnormGD+:
    - concept: ggdonto:CON00147 # Craniofacial Abnormalities
  - ggdonto_schema:brCryptorchidismGD+:
    - concept: ggdonto:CON00466 # Cryptorchidism
  - ggdonto_schema:brDwarfismGD+:
    - concept: ggdonto:CON00158 # Dwarfism
  - ggdonto_schema:brEyeDisHereditaryGD+:
    - clinical_findings_description: ggdonto:CON00487 # Eye Diseases, Hereditary
  - ggdonto_schema:brFootDeformCongenitalGD+:
    - clinical_findings_description: ggdonto:CON00495 # Foot Deformities, Congenital
  - ggdonto_schema:brGastrointestinalDisGD+:
    - clinical_findings_description: ggdonto:CON00175 # Gastrointestinal Diseases
  - ggdonto_schema:brGlaucomaGD+:
    - concept: ggdonto:CON00180 # Glaucoma
  - ggdonto_schema:brHandDeformCongenitalGD+:
    - concept: ggdonto:CON00503 # Hand Deformities, Congenital

