gdgdb_schema: <http://jcggdb.jp/rdf/diseases/gdgdb-schema#>
ggdonto: <http://jcggdb.jp/rdf/diseases/ggdonto#>
ggdonto_schema: <http://jcggdb.jp/rdf/diseases/ggdonto-schema#>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
skos: <http://www.w3.org/2004/02/skos/core#>