- InterviewForm <http://med2rdf.org/if/800126_2590014F1021_1_015_1F>:
  - a: ifo:InterviewForm
  - dct:identifier:
    - if_id: "800126_2590014F1021_1_015_1F"
  - rdfs:seeAlso:
    - pdf: <https://www.info.pmda.go.jp/go/interview/1/800126_2590014F1021_1_015_1F> .
  - ifo:package_insert:
    - package_insert: <http://med2rdf.org/pi/800126_2590014F1021_1_12>
  - ifo:yjcode+:
    - yjcode: YJCode
  - ifo:section+:
    - section: [ IF_0, IF_0_1, IF_0_2, IF_0_3, IF_0_4, IF_0_5, IF_0_6, IF_0_7, IF_0_8, IF_0_9, IF_0_10, IF_0_11, IF_0_12, IF_0_13, IF_0_14, IF_0_15, IF_0_16, IF_0_17, IF_0_18, IF_0_19, IF_0_20, IF_1, IF_1_1, IF_1_2, IF_1_3, IF_1_4, IF_1_4_1, IF_1_4_2, IF_1_4_3, IF_1_4_4, IF_1_5, IF_1_5_1, IF_1_5_2, IF_1_6, IF_2, IF_2_1, IF_2_1_1, IF_2_1_2, IF_2_1_3, IF_2_2, IF_2_2_1, IF_2_2_2, IF_2_2_3, IF_2_3, IF_2_4, IF_2_5, IF_2_6, IF_3, IF_3_1, IF_3_1_1, IF_3_1_2, IF_3_1_3, IF_3_1_4, IF_3_1_5, IF_3_1_6, IF_3_1_7, IF_3_2, IF_3_3, IF_4, IF_4_1, IF_4_1_1, IF_4_1_2, IF_4_1_3, IF_4_1_4, IF_4_1_5, IF_4_2, IF_4_2_1, IF_4_2_2, IF_4_2_3, IF_4_3, IF_4_4, IF_4_5, IF_4_6, IF_4_7, IF_4_8, IF_4_9, IF_4_10, IF_4_10_1, IF_4_10_2, IF_4_10_3, IF_4_10_4, IF_4_11, IF_4_12, IF_5, IF_5_1, IF_5_2, IF_5_3, IF_5_3_1, IF_5_3_2, IF_5_4, IF_5_5, IF_5_5_1, IF_5_5_2, IF_5_5_3, IF_5_5_4, IF_5_5_4_1, IF_5_5_4_2, IF_5_5_5, IF_5_5_6, IF_5_5_6_1, IF_5_5_6_2, IF_5_5_7, IF_6, IF_6_1, IF_6_2, IF_6_2_1, IF_6_2_2, IF_6_2_3, IF_7, IF_7_1, IF_7_1_1, IF_7_1_2, IF_7_1_3, IF_7_1_4, IF_7_2, IF_7_2_1, IF_7_2_2, IF_7_2_3, IF_7_2_4, IF_7_2_5, IF_7_2_6, IF_7_3, IF_7_3_1, IF_7_3_2, IF_7_4, IF_7_5, IF_7_5_1, IF_7_5_2, IF_7_5_3, IF_7_5_4, IF_7_5_5, IF_7_5_6, IF_7_6, IF_7_6_1, IF_7_6_2, IF_7_6_3, IF_7_6_4, IF_7_7, IF_7_8, IF_7_9, IF_7_10, IF_7_11, IF_8, IF_8_1, IF_8_2, IF_8_3, IF_8_4, IF_8_5, IF_8_6, IF_8_6_1, IF_8_6_2, IF_8_6_3, IF_8_6_4, IF_8_6_5, IF_8_6_6, IF_8_6_7, IF_8_6_8, IF_8_7, IF_8_7_1, IF_8_7_2, IF_8_8, IF_8_8_1, IF_8_8_2, IF_8_9, IF_8_10, IF_8_11, IF_8_12, IF_8_12_1, IF_8_12_2, IF_9, IF_9_1, IF_9_1_1, IF_9_1_2, IF_9_1_3, IF_9_2, IF_9_2_1, IF_9_2_2, IF_9_2_3, IF_9_2_4, IF_9_2_5, IF_9_2_6, IF_9_2_7, IF_10, IF_10_1, IF_10_2, IF_10_3, IF_10_4, IF_10_5, IF_10_6, IF_10_7, IF_10_8, IF_10_9, IF_10_10, IF_10_11, IF_10_12, IF_10_13, IF_10_14, IF_11, IF_11_1, IF_11_2, IF_12, IF_12_1, IF_12_2, IF_13 ]

- YJCode yjc:2590014F1021:
  - a: ifo:YJCode
  - ifo:if_0_8:
    - drug_name: "ベタニス錠 25mg"
  - ifo:if_0_9:
    - drug_shape: "フィルムコーティング錠"
  - ifo:if_0_11:
    - drug_規格・含量: "1 錠中にミラベグロン 25mg を含有する。"
  - ifo:if_0_13:
    - drug_製造販売承認年月日: '"2011-07-01"^^xsd:date'
  - ifo:if_0_14:
    - drug_薬価基準収載年月日: '"2011-09-12"^^xsd:date'
  - ifo:if_0_15:
    - drug_販売開始年月日: '"2011-09-16"^^xsd:date'
  - ifo:yakka_code:
    - yakka_code: "2590014F2028"
  - ifo:yj_code:
    - yj_code: "2590014F2028"
  - ifo:hot_code:
    - hot_code: "120933401"
  - ifo:resept_code:
    - resept_code: "622093301"

- IF_0 if:IF_0:
  - a: ifo:IF_0

- IF_0_3 if:IF_0_3:
  - a: ifo:IF_0_3
  - dct:modified:
    - if_modified: '"2019-12"^^xsd:gYearMonth'
  - pav:version:
    - if_version: 15

- IF_0_4 if:IF_0_4:
  - a: ifo:IF_0_4
  - rdf:value:
    - if_日本標準商品分類番号: 87259

- IF_0_6 if:IF_0_6:
  - a: ifo:IF_0_6
  - rdf:value:
    - if_記載要領: '"2018"^^xsd:gYear'

- IF_0_7 if:IF_0_7:
  - a: ifo:IF_0_7
  - rdf:value:
    - if_薬効分類名: "選択的β_3アドレナリン受容体作動性過活動膀胱治療剤"

- IF_0_8 if:IF_0_8:
  - a: ifo:IF_0_8
  - rdf:value:
    - if_名称: "ミラベグロン錠"

- IF_0_10 if:IF_0_10:
  - a: ifo:IF_0_10
  - rdf:value:
    - if_製剤の規制区分: "劇薬、処方箋医薬品(注意-医師等の処方箋により使用すること)"

- IF_0_12 if:IF_0_12:
  - a: ifo:IF_0_12
  - rdf:value:
    - if_一般名：和名・洋名: [ "ミラベグロン(JAN)", "Mirabegron(JAN)" ]

- IF_0_16 if:IF_0_16:
  - a: ifo:IF_0_16
  - rdf:value:
    - if_製造販売: "アステラス製薬株式会社"

- IF_0_18 if:IF_0_18:
  - a: ifo:IF_0_18
  - rdf:value:
    - if_問い合わせ窓口: "アステラス製薬株式会社"

- IF_0_19 if:IF_0_19:
  - a: ifo:IF_0_19
  - rdf:value:
    - if_作成又は改訂年月: '"2019-07"^^xsd:gYearMonth'

- IF_1 if:IF_1:
  - a: ifo:IF_1

- IF_1_1 if:IF_1_1:
  - a: ifo:IF_1_1
  - rdf:value:
    - if_1_1: "過活動膀胱(Overactive Bladder;OAB)について..."
  - dct:references*:
    - if_1_1_ref:
      - if:ref1
      - if:ref2
      - if:ref3
      - if:ref4
      - if:ref5
      - if:ref6
      - if:ref7

- IF_1_2 if:IF_1_2:
  - a: ifo:IF_1_2
  - rdf:value:
    - if_1_2: "1. 日本で開発された世界初の選択的..."
  - rdfs:seeAlso*:
    - if_1_2_xref:
      - if:IF_2_1_1,
      - if:IF_6_2_2_5
      - if:IF_5_5_4_1
      - if:IF_8_8_1

- IF_1_3 if:IF_1_3:
  - a: ifo:IF_1_3
  - rdf:value:
    - if_1_3: "本剤は徐放性製剤であるため、..."
  - rdfs:seeAlso*:
    - if_1_3_xref: if:IF_8_11

- IF_1_4 if:IF_1_4:
  - a: ifo:IF_1_4

- IF_1_4_1 if:IF_1_4_1:
  - a: ifo:IF_1_4_1
  - rdf:value:
    - if_1_4_1: "無"

- IF_1_4_2 if:IF_1_4_2:
  - a: ifo:IF_1_4_2
  - rdf:value:
    - if_1_4_2: "無"
  - rdfs:comment?:
    - if_1_4_2_comment: "医療従事者向け..."
  - rdfs:seeAlso*:
    - if_1_4_2_see_also: if:IF_13


- IF_2_1_1 if:IF_2_1_1:
  - a: ifo:IF_2_1_1
  - rdf:value:
    - if_drug_name: '"ベタニス錠 25mg, べタニス錠 50mg"@ja'

- IF_2_1_3 if:IF_2_1_3:
  - a: ifo:IF_2_1_3
  - rdf:value:
    - derivation: '"Beta 3 agonist より命名した。"@ja'

# <http://med2rdf.org/if/800126_2590014F1021_1_015_1F#IF_8_2.item1> ifo:package_insert <http://med2rdf.org/pi/800126_2590014F1021_1_12#PI_2.item1>

- IF_8_2 if:IF_8_2:
  - a: ifo:IF_8_2
  - ifo:item+:
    - if_8_2_item: IF_8_2_item

- IF_8_2_item if:IF_8_2.item1:
  - a: owl:Class
  - rdf:value:
    - if_8_2_item: "2.2 国内の臨床試験において、..."
  - dct:identifier:
    - if_8_2_id: "8.2.item2"
  - ifo:package_insert:
    - if_8_2_pi: pi:PI_2.item2
  - dct:references*:
    - if_8_2_ref: if:ref15

