- QuantitativeBiologicalDynamicsData ssbd:1a0b3ab7-fc17-45a4-a1d6-29d4cc03f4d5:
  - a: ssbdo:QuantitativeData
  - ssbdo:basedOn:
    - method: "Experiment"
  - ssbdo:correspondingAuthor:
    - depositor: ssbd:depositor148
  - ssbdo:localID:
    - local_id: "FigS2_C5"
  - obo:RO_0002162+: # in taxon
    - node_5: obo:NCBITaxon_10090 # Mus musculus
  - dct:contributor+:
    - depositor: ssbd:depositor148
  - dct:created+:
    - quantitative_biological_dynamics_data_created: 2017-12-20
  - dct:description+:
    - quantitative_biological_dynamics_data_description: "quantiative information about X chromosome structure from Hi-C data at 250-kb resolution for a male mouse T helper (TH1) cell #5 "
  - dct:identifier+:
    - quantitative_biological_dynamics_data_identifier: "1a0b3ab7-fc17-45a4-a1d6-29d4cc03f4d5"
  - dct:license+:
    - resource: ccbyncsa40:
  - dct:references+:
    - resource: pubmed:27725694
  - rdfs:label+:
    - quantitative_biological_dynamics_data_label: "1a0b3ab7-fc17-45a4-a1d6-29d4cc03f4d5"
    - quantitative_biological_dynamics_data_label: "1a0b3ab7-fc17-45a4-a1d6-29d4cc03f4d5"

