sparql:
  description: get proteins in a dataset
  parameters:
    JpostDataset: jpostdb:DS810_1
  variables: [JpostDataset, taxonomy, uniprot, Protein]

sparql_obj_test:
  description: get proteins in a dataset
  parameters:
    JpostDataset: jpostdb:DS810_1
  variables: [JpostDataset, Protein, peptide]
  
peptide_mapping:
  description: peptide mapping
  parameters:
    protein_label: "Q9NYF8"
  variables: [protein_label, Protein, Peptide, aa_sequence, begin, end]

protein_phospho:
  description: phosphorylation position
  parameters:
    protein_label: "Q9NYF8"
  variables: [protein_label, Protein, Peptide, aa_sequence, begin, phospho_position]