title: Ensembl RDF
website: https://www.ensembl.org
description: ゲノム解読された脊椎生物およびその他の主要な真核生物を対象として自動アノテーションを行い、その結果をゲノムビューワやデータベースとして公開しているプロジェクトです。
tags: [Gene, Protein]
provider: EMBL-EBI
creators:
  - name: Shuya Ikeda
    affiliation: Database Center for Life Science
version: 110
issued: 2023-07
licenses:
  - http://ensembl.org/info/about/legal/disclaimer.html
