title: OMA RDF
website: https://omabrowser.org
description: OMA RDF is the a translation of OMA data into RDF.
tags: [Genome, Gene, Phylogeny/Classification]
provider: https://omabrowser.org
creators:
  - name: Name 1
    affiliation: Affiliation 1
version: Nov2022
issued: Nov2022
licenses:
  - Attribution 4.0 International (CC BY 4.0) 
