title: OMA RDF
website: https://omabrowser.org
description: OMA RDF is a translation of OMA data into RDF.
tags: [Genome, Gene, Phylogeny/Classification]
provider:
creators:
  - name: Name 1
    affiliation: Affiliation 1
version: Jul2023
issued: 2023-07-
licenses:
  - Creative Commons Attribution 4.0 International
