sparql:
  description: RDFized reference gene expresson dataset derived from CAGE and GeneChip experiments in the RefEx database.
  variables: [pdb_id, entity_id, chain_id, taxonomy, conf_type, conf_begin_chain_id, sheet_strand_begin_chain_id]
