- ClusterOfOrthologs homologene:3:
  - a: orth:OrthologsCluster
  - orth:hasHomologousMember+:
    - gene: Gene

- Gene ncbigene:34
  - a: orth:Gene
  - rdfs:label:
    - gene_label: "ACADM"
  - orth:taxon:
    - taxon: taxid:9606
  - orth:protein:
    - ncbiprotein: ncbiprotein:NP_000007.1
