rdfs: <http://www.w3.org/2000/01/rdf-schema#>
ncbigene: <http://identifiers.org/ncbigene/>
ncbiprotein: <http://identifiers.org/ncbiprotein/>
homologene: <https://ncbi.nlm.nih.gov/homologene/>
taxid: <http://identifiers.org/taxonomy/>
orth: <http://purl.org/net/orth#>
