rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
owl: <http://www.w3.org/2002/07/owl#>
xl: <http://www.w3.org/2008/05/skos-xl#>
xsd: <http://www.w3.org/2001/XMLSchema#>
dcat: <http://www.w3.org/ns/dcat#>
skos: <http://www.w3.org/2004/02/skos/core#>
vcard: <http://www.w3.org/2006/vcard/ns#>
dc: <http://purl.org/dc/elements/1.1/>
dcterms: <http://purl.org/dc/terms/>
bibo: <http://purl.org/ontology/bibo/>
pav: <http://purl.org/pav/>
tl: <http://purl.org/NET/c4dm/timeline.owl#>
void: <http://rdfs.org/ns/void#>
foaf: <http://xmlns.com/foaf/0.1/>
schema: <http://schema.org/>
dbpo: <http://dbpedia.org/ontology/>
prism: <http://prismstandard.org/namespaces/basic/2.0/>
jst: <http://vocab.jst.go.jp/terms/sti#>
jstd: <http://vocab.jst.go.jp/terms/vlist#>
jstpat: <http://vocab.jst.go.jp/terms/patent#>
ndl: <http://ndl.go.jp/dcndl/terms/>
