rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>
dc: <http://purl.org/dc/elements/1.1/>
faldo: <http://biohackathon.org/resource/faldo#>
obo: <http://purl.obolibrary.org/obo/>
taxonomy: <http://identifiers.org/taxonomy/>
ensg: <http://rdf.ebi.ac.uk/resource/ensembl/>
enso: <http://rdf.ebi.ac.uk/terms/ensembl/>
hgnc: <http://identifiers.org/hgnc/>
hco: <http://identifiers.org/hco/>
ensi: <http://identifiers.org/ensembl/>
ncbigene: <http://identifiers.org/ncbigene/>
omim: <http://identifiers.org/omim/>
uniprot: <http://identifiers.org/uniprot/>
wikigenes: <http://identifiers.org/wikigenes/>
go: <http://identifiers.org/go/>
ena: <http://identifiers.org/ena.embl/>
uniparc: <http://identifiers.org/uniparc/>
reactome: <http://identifiers.org/reactome/R-HSA-2871837>
enst: <http://rdf.ebi.ac.uk/resource/ensembl.transcript/>
ense: <http://rdf.ebi.ac.uk/resource/ensembl.exon/>
ensp: <http://rdf.ebi.ac.uk/resource/ensembl.protein/>
sio: <http://semanticscience.org/resource/>
skos: <http://www.w3.org/2004/02/skos/core#>