evidence: <http://civic.genome.wustl.edu/links/evidence_items/>
gene: <http://civic.genome.wustl.edu/links/genes/>
variants: <http://civic.genome.wustl.edu/links/variants/>
ncbigene: <http://identifiers.org/ncbigene/>
pupmed: <http://identifiers.org/pubmed/>
med2rdf: <http://med2rdf.org/ontology/med2rdf#>
civic: <http://purl.jp/bio/10/civic/>
civico: <http://purl.jp/bio/10/civic/ontology#>
enst: <http://rdf.ebi.ac.uk/resource/ensembl.transcript/>
faldo: <http://biohackathon.org/resource/faldo#>
dct: <http://purl.org/dc/terms/>
rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
rdfs: <http://www.w3.org/2000/01/rdf-schema#>