title: UniProt RDF
website: https://uniprot.org/
description: The Universal Protein Resource (UniProt) is a comprehensive resource for protein sequence and annotation data.
tags: [ Protein ]
provider: The Swiss Institute of Bioinformatics
creators:
  - name: The Swiss Institute of Bioinformatics
version: 2017-04-07
issued: 2017-04-07
licenses:
  - Creative Commons Attribution (CC BY 4.0)
