- Gene ncbigene:34:
  - a: nuc:Gene
  - dct:identifier:
    - id: 34
  - rdfs:label:
    - label: "ACADM"
  - nuc:standard_name?:
    - standard_name: "ACADM"
  - nuc:locus_tag?:
    - locus_tag: ""
  - nuc:gene_synonym*:
    - gene_synonym: "ACAD1"
  - dct:description?:
    - gene_description: "acyl-CoA dehydrogenase medium chain"
  - dct:alternative*:
    - alternative: "medium-chain specific acyl-CoA dehydrogenase, mitochondrial"
  - nuc:dblink*:
    - dblink: hgnc:89
  - nuc:db_xref*:
    - db_xref: "AllianceGenome:HGNC:89"
  - hop:typeOfGene:
    - type_of_gene: "protein-coding"
  - hop:nomenclatureStatus?:
    - nomenclature_status: "official"
  - hop:fullName?:
    - full_name: "acyl-CoA dehydrogenase medium chain"
  - hop:featureType*:
    - feature_type: ""
  - hop:taxid:
    - taxid: taxid:9606
  - nuc:chromosome*:
    - chromosome: 1
  - nuc:map*:
    - map: "1p31.1"
  - dct:modified:
    - modified: "2021-02-07"
