- Gene ncbigene:34:
  - a: nuc:Gene
  - rdfs:label:
    - gene_label: "ACADM"
  - nuc:standard_name:
    - standard_name: "ACADM"
  - nuc:gene_synonym+:
    - gene_synonym: "ACAD1"
  - dct:description:
    - gene_description: "acyl-CoA dehydrogenase medium chain"
  - dct:alternative:
    - alternative: "medium-chain specific acyl-CoA dehydrogenase, mitochondrial"
  - nuc:dblink:
    - dblink: 607008
  - hop:typeOfGene:
    - type_of_gene: "protein-coding"
  - hop:nomenclatureStatus:
    - nomenclature_status: "official"
  - nuc:chromosome:
    - chromosome: 1
  - nuc:map:
    - map: "1p31.1"
  - dct:modified:
    - modified: "2021-02-07"
