- Cluster cluster:2018-01_default_3927:
  - a: orth:OrthologsCluster
  - mbgd:dist:
    - node_2: 0
  - mbgd:funcCog:
    - node_3: "4.2"
  - mbgd:funcKegg:
    - node_4: "1.2"
  - mbgd:funcMbgd:
    - node_5: "6"
  - mbgd:funcTigr:
    - node_6: "6.15"
  - mbgd:score:
    - node_7: 0
  - dct:description:
    - node_8: "Photosystem II reaction center protein"
  - dct:identifier:
    - node_9: "3927"
  - orth:hasHomologous+:
    - node_10: domain:0
    - gene: Gene
  - void:inDataset:
    - dataset: Dataset
  - rdfs:label:
    - node_14: "psbA"
  - foaf:page:
    - node_15: bin:hcluster?prog=hcluster&amp;clustid=O3927&amp;tabid=default

- Gene p246:DACSA_RS08170:
  - a:
    - orth:Gene
    - mbgd:CDS
  - mbgd:aaLength:
    - node_18: 353
  - mbgd:domain:
    - node_19: p35:0
  - mbgd:nucSeq:
    - nucseq: Nucseq # Chromosome 1
  - mbgd:organism:
    - organism: Organism
  - mbgd:protein:
    - node_22: ncbiprotein:WP_015229298.1
  - mbgd:taxon:
    - taxon: taxid:13035 # Dactylococcopsis salina PCC 8305
  - mbgd:uniprot:
    - node_24: uniprot:K9YTN9
  - obo:RO_0002162: # in taxon
    - taxon: taxid:13035 # Dactylococcopsis salina PCC 8305
  - dct:description:
    - node_26: "photosystem II DII subunit, Q(A) protein"
  - dct:identifier:
    - node_27: "dsl:DACSA_RS08170"
  - dct:source:
    - node_28: ncbi:refseq
  - sio:SIO_000028:
    - node_19: p35:0
  - sio:SIO_010078+:
    - node_24: uniprot:K9YTN9
    - node_22: ncbiprotein:WP_015229298.1
  - rdfs:label:
    - node_32: ""
  - foaf:page:
    - node_33: p330:DACSA_RS08170

- Dataset resource:default:
  - a:
    - void:Dataset
    - orth:OrthologyDataset
  - dct:created:
    - node_74: 2018-09-20T14:36:24+09:00
  - dct:creator:
    - node_75: p297:mbgd.genome.ad.jp
  - dct:description:
    - node_76: "RDF representation of ortholog groups in MBGD."
  - dct:license:
    - node_77: https://creativecommons.org/licenses/by-sa/4.0/
  - dct:publisher:
    - node_78: p297:www.nibb.ac.jp
  - dct:source:
    - node_75: p297:mbgd.genome.ad.jp
  - dct:title:
    - node_80: "MBGD ortholog groups"
  - pav:derivedFrom:
    - node_81: p299:mbgd_2018-01_default.dclst.gz
  - pav:version:
    - node_82: "2018-01"
  - void:dataDump:
    - node_83: p300:mbgd_2018-01_default.ttl.gz
  - foaf:page:
    - node_84: bin:cluster_map?tabid=default&amp;show_summary=1

- Nucseq nucseq:13397:
  - a:
    - mbgd:Chromosome
    - mbgd:Circular
  - mbgd:geneCount:
    - node_67: 3437
  - mbgd:nucLength:
    - node_68: 3781008
  - dct:identifier:
    - node_69: 1
  - rdfs:label:
    - node_70: "Chromosome 1"
  - rdfs:seeAlso:
    - node_71: p289:NC_019780.1

- Organism organism:dsl:
  - a:
    - mbgd:Genome
    - mbgd:CompleteGenome
  - mbgd:abbrev:
    - node_36: "D.salina"
  - mbgd:assembly:
    - node_37: p283:GCF_000317615.1
  - mbgd:assemblyContigCount:
    - node_38: 0
  - mbgd:assemblyContigN50:
    - node_39: 0
  - mbgd:assemblyLevel:
    - node_40: "Complete Genome"
  - mbgd:assemblyMoleculeCount:
    - node_41: 1
  - mbgd:assemblyTopLevelCount:
    - node_42: 1
  - mbgd:assemblyTotalGapLength:
    - node_43: 0
  - mbgd:assemblyTotalLength:
    - node_44: 3781008
  - mbgd:family:
    - node_45: ""
  - mbgd:genus:
    - node_46: "Dactylococcopsis"
  - mbgd:inFamily:
    - taxon: taxid:1890426 # Synechococcaceae
  - mbgd:inGenus:
    - taxon: taxid:13034 # Dactylococcopsis
  - mbgd:inOrder:
    - taxon: taxid:1890424 # Synechococcales
  - mbgd:inPhylum:
    - taxon: taxid:1117 # Cyanobacteria
  - mbgd:inSpecies:
    - taxon: taxid:292566 # Dactylococcopsis salina
  - mbgd:inSuperkingdom:
    - taxon: taxid:2
  - mbgd:inTaxon:
    - taxon: taxid:1117 # Cyanobacteria
  - mbgd:species:
    - node_54: "Dactylococcopsis salina"
  - mbgd:spid:
    - node_55: "gm02198"
  - mbgd:strain:
    - node_56: "PCC 8305"
  - mbgd:unlocalizedTotalLength:
    - node_57: 0
  - mbgd:unlocalizedUngappedLength:
    - node_58: 0
  - obo:RO_0002162: # in taxon
    - taxon: taxid:13035 # Dactylococcopsis salina PCC 8305
  - dct:identifier:
    - node_60: "dsl"
  - dct:issued:
    - node_61: 2012-12-07+09:00
  - up:organism:
    - node_62: uptax:13035
  - rdfs:label:
    - node_63: "Dactylococcopsis salina PCC 8305"
  - foaf:page:
    - node_64: bin:MBGD_whole_html.pl?spec=dsl

